'use client';

import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { FileText, Shield, Users, AlertTriangle, CheckCircle, Clock, Mail } from 'lucide-react';
import { Layout } from '@/components/layout/Layout';

export default function TermsPage() {
  const lastUpdated = 'December 12, 2024';

  const sections = [
    {
      id: 'acceptance',
      title: 'Acceptance of Terms',
      icon: CheckCircle,
      content: `By accessing and using CopeCompanion, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.`
    },
    {
      id: 'description',
      title: 'Service Description',
      icon: FileText,
      content: `CopeCompanion is a mental health support platform that provides AI-powered conversations, community support, progress tracking, and access to mental health resources. Our services are designed to complement, not replace, professional mental health care.`
    },
    {
      id: 'user-accounts',
      title: 'User Accounts and Registration',
      icon: Users,
      content: `To access certain features, you must register for an account. You agree to provide accurate, current, and complete information and to update this information as necessary. You are responsible for maintaining the confidentiality of your account credentials.`
    },
    {
      id: 'acceptable-use',
      title: 'Acceptable Use Policy',
      icon: Shield,
      content: `You agree not to use the service for any unlawful purposes or to conduct any unlawful activity. This includes but is not limited to: harassment, threats, hate speech, sharing harmful content, or attempting to compromise the security of our platform.`
    },
    {
      id: 'mental-health',
      title: 'Mental Health Support Disclaimer',
      icon: AlertTriangle,
      content: `CopeCompanion is not a substitute for professional mental health treatment. Our AI conversations and community support are supplementary tools. In case of mental health crisis, please contact emergency services or qualified mental health professionals immediately.`
    },
    {
      id: 'privacy',
      title: 'Privacy and Data Protection',
      icon: Shield,
      content: `Your privacy is important to us. We collect and process personal information in accordance with our Privacy Policy and applicable data protection laws. We implement appropriate technical and organizational measures to protect your personal data.`
    },
    {
      id: 'content-ownership',
      title: 'Content Ownership and Rights',
      icon: FileText,
      content: `You retain ownership of content you create. By using our service, you grant us a limited license to use, store, and process your content to provide our services. We respect your intellectual property rights and those of third parties.`
    },
    {
      id: 'termination',
      title: 'Account Termination',
      icon: Users,
      content: `We reserve the right to terminate or suspend your account at our discretion, particularly if you violate these terms. You may also terminate your account at any time through your account settings.`
    },
    {
      id: 'disclaimers',
      title: 'Disclaimers and Limitations',
      icon: AlertTriangle,
      content: `The service is provided "as is" without warranties. We do not guarantee uninterrupted service. Our liability is limited to the maximum extent permitted by law. AI responses are generated by machine learning models and may not always be accurate.`
    },
    {
      id: 'governing-law',
      title: 'Governing Law',
      icon: Shield,
      content: `These terms are governed by the laws of [Jurisdiction]. Any disputes will be resolved through binding arbitration in accordance with the rules of the American Arbitration Association.`
    }
  ];

  return (
    <Layout>
      <div className="max-w-4xl mx-auto p-6 space-y-6">
        {/* Header */}
        <div className="text-center">
          <div className="flex items-center justify-center gap-3 mb-4">
            <FileText className="h-12 w-12 text-blue-600" />
            <h1 className="text-4xl font-bold text-gray-900">Terms of Service</h1>
          </div>
          <p className="text-lg text-gray-600">
            Last updated: {lastUpdated}
          </p>
          <Badge className="mt-2 bg-blue-100 text-blue-800">Version 1.0</Badge>
        </div>

        {/* Important Notice */}
        <Alert className="bg-yellow-50 border-yellow-200">
          <AlertTriangle className="h-4 w-4 text-yellow-600" />
          <AlertDescription className="text-yellow-800">
            <strong>Important:</strong> Please read these terms carefully. By using CopeCompanion,
            you agree to be bound by these terms. If you do not agree, please do not use our service.
          </AlertDescription>
        </Alert>

        {/* Table of Contents */}
        <Card>
          <CardHeader>
            <CardTitle>Table of Contents</CardTitle>
            <CardDescription>Quick navigation to different sections</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
              {sections.map((section) => (
                <a
                  key={section.id}
                  href={`#${section.id}`}
                  className="flex items-center gap-2 p-2 rounded hover:bg-gray-50 transition-colors"
                >
                  <section.icon className="h-4 w-4 text-blue-600" />
                  <span className="text-sm">{section.title}</span>
                </a>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Terms Content */}
        <div className="space-y-6">
          {sections.map((section, index) => (
            <Card key={section.id} id={section.id}>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <section.icon className="h-5 w-5 text-blue-600" />
                  {index + 1}. {section.title}
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-gray-700 leading-relaxed">{section.content}</p>
              </CardContent>
            </Card>
          ))}
        </div>

        {/* Contact Information */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Mail className="h-5 w-5" />
              Questions About These Terms?
            </CardTitle>
            <CardDescription>
              If you have any questions about these Terms of Service, please contact us
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <h4 className="font-medium mb-2">Legal Inquiries</h4>
                <p className="text-sm text-gray-600">
                  Email: legal@copecompanion.com<br />
                  Phone: 1-800-HELP-NOW (ext. 123)
                </p>
              </div>
              <div>
                <h4 className="font-medium mb-2">General Support</h4>
                <p className="text-sm text-gray-600">
                  Email: support@copecompanion.com<br />
                  Phone: 1-800-HELP-NOW
                </p>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Acceptance */}
        <Card>
          <CardHeader>
            <CardTitle>Acceptance of Terms</CardTitle>
            <CardDescription>
              By continuing to use CopeCompanion, you acknowledge that you have read and agree to these terms
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="flex items-center gap-4">
              <Button className="bg-green-600 hover:bg-green-700">
                <CheckCircle className="h-4 w-4 mr-2" />
                I Accept These Terms
              </Button>
              <Button variant="outline">
                Print Terms
              </Button>
              <Button variant="outline">
                Download PDF
              </Button>
            </div>
            <p className="text-sm text-gray-600 mt-4">
              These terms are effective as of {lastUpdated}. We may update these terms periodically.
              Your continued use of the service constitutes acceptance of any changes.
            </p>
          </CardContent>
        </Card>

        {/* Footer */}
        <div className="text-center text-sm text-gray-600">
          <p>© 2024 CopeCompanion. All rights reserved.</p>
          <div className="flex items-center justify-center gap-4 mt-2">
            <a href="/privacy" className="hover:text-blue-600">Privacy Policy</a>
            <span>•</span>
            <a href="/accessibility" className="hover:text-blue-600">Accessibility</a>
            <span>•</span>
            <a href="/contact" className="hover:text-blue-600">Contact Us</a>
          </div>
        </div>
      </div>
    </Layout>
  );
}